/** @filedesc WASM bridge — lazy initialization and typed wrappers for all Rust WASM exports. */

// The wasm-pkg is generated by wasm-pack with --target web.
// It exports an async init() default function that must be called before any
// other export is usable, plus a synchronous initSync() variant.

let _wasmReady = false;
let _initPromise: Promise<void> | null = null;

/** Whether the WASM module has been initialized and is ready for use. */
export function isWasmReady(): boolean {
    return _wasmReady;
}

/**
 * Initialize the WASM module. Safe to call multiple times — subsequent calls
 * return the same promise. Resolves when WASM is ready; rejects on failure.
 */
export async function initWasm(): Promise<void> {
    if (_wasmReady) return;
    if (_initPromise) return _initPromise;

    _initPromise = (async () => {
        try {
            // Dynamic import so the WASM glue is only loaded when needed
            const mod = await import('../wasm-pkg/formspec_wasm.js');
            // wasm-pack default export is the init function; TypeScript's
            // module namespace typing doesn't always recognise it as callable,
            // so we import by name from the generated types.
            const init: (input?: any) => Promise<any> = (mod as any).default;
            await init();
            _wasm = mod;
            _wasmReady = true;
        } catch (e) {
            _initPromise = null;
            throw e;
        }
    })();

    return _initPromise;
}

// ---------------------------------------------------------------------------
// Module accessor — cached by initWasm, synchronous after initialization
// ---------------------------------------------------------------------------

let _wasm: typeof import('../wasm-pkg/formspec_wasm.js') | null = null;

/** Synchronous accessor — throws if WASM is not initialized. */
function wasm(): typeof import('../wasm-pkg/formspec_wasm.js') {
    if (!_wasm || !_wasmReady) {
        throw new Error('WASM not initialized. Call initWasm() first.');
    }
    return _wasm;
}

// ---------------------------------------------------------------------------
// Typed wrappers — each delegates to the WASM export with JSON marshalling
// ---------------------------------------------------------------------------

/** Evaluate a FEL expression with optional field values. Returns the evaluated result. */
export function wasmEvalFEL(expression: string, fields: Record<string, any> = {}): any {
    const resultJson = wasm().evalFEL(expression, JSON.stringify(fields));
    return JSON.parse(resultJson);
}

/** Parse a FEL expression and return whether it's valid. */
export function wasmParseFEL(expression: string): boolean {
    return wasm().parseFEL(expression);
}

/** Extract field path dependencies from a FEL expression. Returns an array of path strings. */
export function wasmGetFELDependencies(expression: string): string[] {
    const resultJson = wasm().getFELDependencies(expression);
    return JSON.parse(resultJson);
}

/** Extract full dependency info from a FEL expression. */
export function wasmExtractDependencies(expression: string): {
    fields: string[];
    contextRefs: string[];
    instanceRefs: string[];
    mipDeps: string[];
    hasSelfRef: boolean;
    hasWildcard: boolean;
    usesPrevNext: boolean;
} {
    const resultJson = wasm().extractDependencies(expression);
    return JSON.parse(resultJson);
}

/** Normalize a dotted path by stripping repeat indices. */
export function wasmNormalizeIndexedPath(path: string): string {
    return wasm().normalizeIndexedPath(path);
}

/** Detect the document type of a Formspec JSON document. */
export function wasmDetectDocumentType(doc: unknown): string | null {
    const result = wasm().detectDocumentType(JSON.stringify(doc));
    return result === null ? null : result;
}

/** Assemble a definition by resolving $ref inclusions. */
export function wasmAssembleDefinition(
    definition: unknown,
    fragments: Record<string, unknown>,
): { definition: any; warnings: string[]; errors: string[] } {
    const resultJson = wasm().assembleDefinition(
        JSON.stringify(definition),
        JSON.stringify(fragments),
    );
    return JSON.parse(resultJson);
}

/** Execute a mapping transform. */
export function wasmExecuteMapping(
    rules: unknown[],
    source: unknown,
    direction: 'forward' | 'reverse',
): { direction: string; output: any; rulesApplied: number; diagnostics: any[] } {
    const resultJson = wasm().executeMapping(
        JSON.stringify(rules),
        JSON.stringify(source),
        direction,
    );
    return JSON.parse(resultJson);
}

/** Execute a full mapping document (rules + defaults + autoMap). */
export function wasmExecuteMappingDoc(
    doc: unknown,
    source: unknown,
    direction: 'forward' | 'reverse',
): { direction: string; output: any; rulesApplied: number; diagnostics: any[] } {
    const resultJson = wasm().executeMappingDoc(
        JSON.stringify(doc),
        JSON.stringify(source),
        direction,
    );
    return JSON.parse(resultJson);
}

/** Lint a Formspec document. */
export function wasmLintDocument(doc: unknown): {
    documentType: string | null;
    valid: boolean;
    diagnostics: any[];
} {
    const resultJson = wasm().lintDocument(JSON.stringify(doc));
    return JSON.parse(resultJson);
}

/** Evaluate a Formspec definition against provided data. */
export function wasmEvaluateDefinition(
    definition: unknown,
    data: Record<string, unknown>,
): { values: any; validations: any[]; nonRelevant: string[]; variables: any } {
    const resultJson = wasm().evaluateDefinition(
        JSON.stringify(definition),
        JSON.stringify(data),
    );
    return JSON.parse(resultJson);
}

/** Analyze a FEL expression and return structural info. */
export function wasmAnalyzeFEL(expression: string): {
    valid: boolean;
    errors: string[];
    references: string[];
    variables: string[];
    functions: string[];
} {
    const resultJson = wasm().analyzeFEL(expression);
    return JSON.parse(resultJson);
}
