#!/usr/bin/env python3
"""Generate a single consolidated Markdown API doc from the formspec Python package for LLM context."""

import re
import sys
from pathlib import Path

import pdoc.doc
import pdoc.extract


def short_type(s: str) -> str:
    """Strip module prefixes from type annotations: formspec.fel.types.FelNumber -> FelNumber."""
    return re.sub(r"formspec\.\w+(?:\.\w+)*\.(\w+)", r"\1", str(s))


def fmt_sig(member) -> str:
    sig = getattr(member, "signature", None)
    if sig is None:
        return ""
    return short_type(str(sig))


def write_function(f, func, heading="#####"):
    sig = fmt_sig(func)
    f.write(f"{heading} `{func.name}{sig}`\n\n")
    if func.docstring:
        f.write(f"{func.docstring.strip()}\n\n")


def write_class(f, cls):
    f.write(f"#### class `{cls.name}`\n\n")
    if cls.docstring:
        f.write(f"{cls.docstring.strip()}\n\n")
    for member in cls.own_members:
        if member.name.startswith("_") and member.name != "__init__":
            continue
        if member.kind == "function":
            write_function(f, member)
        elif member.kind == "variable" and member.docstring:
            f.write(f"- **{member.name}**: {member.docstring.strip()}\n")
    f.write("\n")


def write_module(f, mod, depth=2):
    prefix = "#" * depth
    f.write(f"{prefix} `{mod.fullname}`\n\n")
    if mod.docstring:
        f.write(f"{mod.docstring.strip()}\n\n")

    for func in mod.functions:
        if func.name.startswith("_"):
            continue
        write_function(f, func, heading=prefix + "##")

    for cls in mod.classes:
        if cls.name.startswith("_"):
            continue
        write_class(f, cls)

    for sub in mod.submodules:
        submod = pdoc.doc.Module(pdoc.extract.load_module(sub.fullname))
        write_module(f, submod, depth=depth + 1)


def main():
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("src/formspec/API.llm.md")
    out_path.parent.mkdir(parents=True, exist_ok=True)

    root = pdoc.doc.Module(pdoc.extract.load_module("formspec"))

    with open(out_path, "w") as f:
        f.write("# formspec (Python) — API Reference\n\n")
        f.write("*Auto-generated by pdoc — do not hand-edit.*\n\n")
        if root.docstring:
            f.write(f"{root.docstring.strip()}\n\n")

        for sub in root.submodules:
            submod = pdoc.doc.Module(pdoc.extract.load_module(sub.fullname))
            f.write(f"## `formspec.{sub.name}`\n\n")
            if submod.docstring:
                f.write(f"{submod.docstring.strip()}\n\n")

            for func in submod.functions:
                if func.name.startswith("_"):
                    continue
                write_function(f, func, heading="###")

            for cls in submod.classes:
                if cls.name.startswith("_"):
                    continue
                write_class(f, cls)

            for subsub in submod.submodules:
                subsubmod = pdoc.doc.Module(pdoc.extract.load_module(subsub.fullname))
                write_module(f, subsubmod, depth=3)

    print(f"  {out_path}")


if __name__ == "__main__":
    main()
